### ISSUE TITLE
Cannot find module declaration for module 'electron-titlebar'

### ISSUE THREAD

**Issue by murermader** [Menci/electron-titlebar#15]
First of all, I am super to new to electron, so sorry is this is a stupid question. I followed the readme, but I can't seem to get it to work.

I put `require('electron-titlebar')` at the top of my main.js file, where I am also importing electron. But I get this error here:

![image](https://user-images.githubusercontent.com/46532999/74591088-31e75180-5015-11ea-8792-4e791ef54978.png)

I tried installing the npm install tip, and I don't think the d.ts (I am not using typescript) is the right guess from that error message.

Changing the path from `electron-titlebar` to something like `./node_modules/electron-titlebar` did not help either.

Running the app gives me this error message: 

![image](https://user-images.githubusercontent.com/46532999/74591202-1761a800-5016-11ea-8d42-0253ae223717.png)

---
I am using windows 1908, node 12.13.0, Chrome 80.0.3987.86, and Electron 8.0.1.

**Comment by Menci** [comment]
You should require `electron-titlebar` in your renderer process (i.e. in your HTML `<script>`).
