### ISSUE TITLE
div with position:relative

### ISSUE THREAD

**Issue by kaiwildberger** [Menci/electron-titlebar#16]
When I launch my application, the `electron-titlebar` element is not at the top.
![image](https://user-images.githubusercontent.com/53071526/90277513-9ba4b480-de1a-11ea-86ea-a7d0d79228e1.png)

Upon inspection, I see a div with relative positioning around the titlebar which is pushing it down the page. I removed the wrapper div and the titlebar scooted back up to the top.
![image](https://user-images.githubusercontent.com/53071526/90278018-88deaf80-de1b-11ea-9aa3-6335639369ac.png)

Of course I could get rid of it in my js file, but I wanted to ask about it and see if I could find a better way to remove it.

thanks

**Comment by Menci** [comment]
It doesn't look like to be my titlebar that took the height. My titlebar shouldn't take width and height since I used a `position: relative; ` outside and a `position: absolute; ` inside. Can you provide a minimal working example for me?

**Comment by kaiwildberger** [comment]
hEh i had by body tag's margin-top set to 2em

sorry about that
