### ISSUE TITLE
Screenshots pls

### ISSUE THREAD

**Issue by benavern** [Menci/electron-titlebar#3]
Hi, 
I'm very interested in that project but can't test it now. 
Could you put screenshots of the 3 themes in the readme, so that I'll think in putting your project in my favourites?

Thank you in advance
Benjamin

**Comment by samuel-allan** [comment]
In general I agree because screenshots are really helpful in these kinds of projects.

**Comment by benavern** [comment]
Can't wait to see theme. While waiting could you make the pr or put some in this issue so that @Menci could use theme in his readme?
Thanks!

**Comment by Slapbox** [comment]
Package sounds cool, but without a screenshot I can't afford to spend the time implementing it to find out it doesn't meet my needs. Screenshots would be great.

**Comment by ziyaointl** [comment]
#6 I just added the screenshots. Hope that helps.
