### ISSUE TITLE
I try to put link the title bar

### ISSUE THREAD

**Issue by dariomadeira** [Menci/electron-titlebar#5]
I try to put a link the title bar but it does not work when I put <a> </a>. Some example to know how to do it. Thank you!

    <div id="electron-titlebar" platform="win32" class="titulo inset">
      <div class="drag arrastre"></div>
      <div class="back_btn">
        <a href="#" onclick="console.log('click');" class="fa2 mi mi-LeftArrowKeyTime0 mi-22x"></a>
      </div>
      <div class="titulo_data" id="titul"></div>
    </div>

.arrastre {
	top: 0;
	left: 54px;
	width: 100%;
	height: 100%;
	position: absolute;
}
.back_btn {
	width: 50px; 
	height: 100%; 
	line-height: 40px; 
	background-color: #27003b;
	float:left;
}
.titulo_data {
	left: 60px;
	width: 100%; 
	height: 100%; 
	text-align: left; 
	line-height: 40px; 
	color: white;
	position: absolute;
}

**Comment by lunananananananana** [comment]
I'm assuming you mean it's visible but not clickable in this comment. If it's something else, this probably won't work.

You should try adding `-webkit-app-region: no-drag;`, otherwise the link will just be used as a draggable area on the titlebar.
