### ISSUE TITLE
Getting 'document is not defined' ReferenceError

### ISSUE THREAD

**Issue by JonSn0w** [Menci/electron-titlebar#8]
I'm fairly new to node.js and electron, so assuming this most likely a result of user error, but I've been repeatedly unsuccessful in finding a solution. 
The error message only references the following lines: 
```javascript
if (document.readyState === 'complete' || document.readyState === 'interactive') installTitlebar();
else document.addEventListener('DOMContentLoaded', installTitlebar);
```
Let me know if more information is needed and I apologize beforehand if this is a stupid question.

**Comment by JonSn0w** [comment]
Sorry, I finally realized I was requiring the module in the wrong file directly after posting this.

**Comment by prionkor** [comment]
@tterb kindly leave more info when you solve a problem that help other who are facing the same issue :)

**Comment by lunananananananana** [comment]
The solution is not to require the package in the main process, but in the renderer process instead
